
"""
CRITICAL: Do NOT edit this file after Hour 1 without team agreement!
"""
from typing import Optional, List, Dict
from pydantic import BaseModel


# Input to Scout
class ScanInput(BaseModel):
    url: str
    scanType: str  # "page" | "email" | "message" | "image"
    content: Optional[str] = None
    image_data: Optional[str] = None  # base64 for screenshots


# Output from Scout -> Input to Analyst
class ScoutOutput(BaseModel):
    scanType: str
    initialRisk: int  # 0-100
    signals: Dict
    recommendation: str  # "ESCALATE_TO_ANALYST" | "SAFE" | "BLOCK"
    predictiveWarning: Optional[str] = None


# Output from Analyst -> Input to Educator
class AnalystOutput(BaseModel):
    analysisId: str
    threatType: str  # "phishing" | "scam" | "malware" | "privacy_violation"
    riskScore: int  # 0-100
    confidence: float  # 0.0-1.0
    evidence: List[Dict]
    mitreAttackTechniques: List[str]


# Output from Educator -> Final Output
class EducatorOutput(BaseModel):
    explanation: str
    nextSteps: List[str]
    learningPoints: List[str]
    voiceAlert: Optional[str] = None


# Final Combined Output (Person D assembles)
class ScanResult(BaseModel):
    scanId: str
    timestamp: str
    url: str
    scanType: str
    riskScore: int
    threatType: str
    confidence: float
    evidence: List[Dict]
    explanation: str
    nextSteps: List[str]

